from abc import ABC, abstractmethod
import pyannote.pipeline
import whisperx
import pyannote.audio
import torch
import torchaudio
import numpy as np
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import linkage, fcluster
import subprocess
import glob
import shutil
import os
import time
from silero_vad import load_silero_vad, read_audio, get_speech_timestamps
import math
import typing
from typing import Optional

import librosa
import sounddevice as sd


from utilities.strategies.output_strategy import OutputFormatStrategyFactory
from types import MappingProxyType
from utilities.pipeline_context import PipelineContext


class TranscriptionStrategy(ABC):
    @abstractmethod
    def process(
        self,
        input_files: list[str],
        output_dir: str,
        clip_dir: str,
        initial_prompt: Optional[str],
        output_types: list[str],
        language: Optional[str],
        speakers_min: Optional[int],
        speakers_max: Optional[int],
        speaker_count: Optional[int],
        output_base_name: Optional[str],
        model_name: str,
        pipeline_context: Optional[PipelineContext],
    ) -> None:
        pass

    def _generate_outputs(
            self,
            input_files: list[str],
            output_dir: str,
            output_types: list[str],
            segments: list[dict],
            output_base_name: Optional[str] = None
    ) -> None:
        """Write labeled segments with text, speaker, timestamps to selected file format(s)"""
        now = int(time.time())
        base_name = output_base_name if output_base_name else os.path.splitext(os.path.basename("_".join(input_files)))[0]

        for tp in output_types:
            strategy = OutputFormatStrategyFactory.get_strategy(tp)
            strategy.output(segments, output_dir, now, base_name)

    def _handle_large_files(self, input_file, clip_dir) -> list[str]:
        """Determine if file size exceeds 1 GB, split if yes."""
        if os.path.getsize(input_file) > 1_073_741_824: # = 1GB
            return self._split_audio(input_file, clip_dir)
        else:
            clip_path = os.path.join(clip_dir, "original" + os.path.splitext(input_file)[1])
            shutil.copy(input_file, clip_path)
            return [clip_path]

    def _split_audio(self, input_file:str, clip_dir: str, segment_time: int=3600):
        """Perform audio splitting."""
        base_name = os.path.splitext(os.path.basename(input_file))[0]
        clip_subdir = os.path.join(clip_dir, base_name)
        os.makedirs(clip_subdir, exist_ok=True)
        output_pattern = os.path.join(clip_subdir, "clip%03d" + os.path.splitext(input_file)[1])
        cmd = ['ffmpeg', '-i', input_file, '-f', 'segment', '-segment_time', str(segment_time), '-c', 'copy', output_pattern]
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return sorted(glob.glob(os.path.join(clip_subdir, "clip*")))
    
    def _cleanup_clips(self, clips: list[str], clip_dir: str) -> None:
        """Remove clips generated by _handle_large_files > _split_audio clips after processing."""
        for clip in clips:
            os.path.join(clip_dir, clip)
            try:
                os.remove(clip)
            except Exception as e:
                print(e)


class NonDiarizedSingleStreamStrategy(TranscriptionStrategy):
    """Transcribes single or multi-stream audio as a single speaker."""
    def process(self, input_files, output_dir, clip_dir, initial_prompt, output_types, language, speakers_min, speakers_max, speaker_count, output_base_name, model_name) -> None:
        whisper_model = whisperx.load_model(
            whisper_arch=model_name,
            device="cuda",
            compute_type="float16",
            language=language
        )
        whisper_model.options.initial_prompt = initial_prompt
        for input_file in input_files:
            result = whisper_model.transcribe(input_file, print_progress=True)
            segments = result["segments"]
            self._generate_outputs([input_file], output_dir, output_types, segments, output_base_name)


class DiarizedSingleStreamStrategy(TranscriptionStrategy):
    """Transcribes single-stream audio with speaker diarization."""
    def process(self, input_files, output_dir, clip_dir, initial_prompt, output_types, language, speakers_min, speakers_max, speaker_count, output_base_name, model_name) -> None:
        whisper_model = whisperx.load_model(
            whisper_arch=model_name,
            device="cuda",
            compute_type="float16",
            language=language
        )
        whisper_model.options.initial_prompt = initial_prompt
        embedding_model = pyannote.audio.Inference("pyannote/embedding", device=torch.device("cuda"))
        for input_file in input_files:
            clips = self._handle_large_files(input_file, clip_dir)
            all_segments = []
            for clip_path in clips:
                result = whisper_model.transcribe(clip_path, tqdm_progress=True)
                segments = result["segments"]
                for segment in segments:
                    sample_rate = torchaudio.info(clip_path).sample_rate
                    waveform, _ = torchaudio.load(clip_path, frame_offset=int(segment["start"] * sample_rate), num_frames=int((segment["end"] - segment["start"]) * sample_rate))
                    embedding_tensor = embedding_model({"waveform": waveform, "sample_rate": sample_rate})
                    embedding = embedding_tensor.data.mean(axis=0)
                    all_segments.append({"start": segment["start"], "end": segment["end"], "text": segment["text"], "embedding": embedding})
            if all_segments:
                embeddings = np.array([seg["embedding"].data for seg in all_segments])
                dist_matrix = pdist(embeddings, metric='cosine')
                linkage_matrix = linkage(dist_matrix, method='average')
                clusters = fcluster(linkage_matrix, t=0.5, criterion='distance')
                unique_clusters = np.unique(clusters)
                speaker_map = {cluster: f"Speaker {i+1}" for i, cluster in enumerate(unique_clusters)}
                for i, segment in enumerate(all_segments):
                    segment["speaker"] = speaker_map[clusters[i]]
                    del segment["embedding"]
                sorted_segments = sorted(all_segments, key=lambda x: x["start"])

                self._generate_outputs([input_file], output_dir, output_types, sorted_segments, output_base_name)


class NonDiarizedMultiStreamStrategy(TranscriptionStrategy):
    """Transcribes multi-stream audio, each stream as a different speaker."""
    def process(self, input_files, output_dir, clip_dir, initial_prompt, output_types, language, speakers_min, speakers_max, speaker_count, output_base_name, model_name) -> None:
        whisper_model = whisperx.load_model(
            whisper_arch=model_name,
            device="cuda",
            compute_type="float16",
            language=language
        )
        whisper_model.options.initial_prompt = initial_prompt
        for idx, input_file in enumerate(input_files):
            speaker = f"Speaker {idx + 1}"
            result = whisper_model.transcribe(input_file, tqdm_progress=True)
            segments = result["segments"]
            # self._generate_outputs(input_file, output_dir, output_types, segments, speaker)
            self._generate_outputs(input_file, output_dir, output_types, segments, output_base_name)


class NonDiarizedAlignedFilesStrategy(TranscriptionStrategy):
    """Transcribes multiple aligned files, each as a separate speaker, into a combined output."""
    def process(self, input_files, output_dir, clip_dir, initial_prompt, output_types, language, speakers_min, speakers_max, speaker_count, output_base_name, model_name) -> None:
        whisper_model = whisperx.load_model(
            whisper_arch=model_name,
            device="cuda",
            compute_type="float16",
            language=language
        )
        whisper_model.options.initial_prompt = initial_prompt
        all_segments = []
        for idx, input_file in enumerate(input_files):
            speaker_candidate_name = os.path.basename(input_file).split('.')[0]
            speaker = f"Speaker {idx + 1} ({speaker_candidate_name})"
            result = whisper_model.transcribe(input_file, tqdm_progress=True)
            segments = result["segments"]
            for seg in segments:
                all_segments.append({"start": seg["start"], "end": seg["end"], "text": seg["text"], "speaker": speaker})
        sorted_segments = sorted(all_segments, key=lambda x: x["start"])
        self._generate_outputs(input_files, output_dir, output_types, sorted_segments, output_base_name)


class TranscriptionStrategyFactory():
    _strategy_mapping = MappingProxyType({
        'non-diarized-single': NonDiarizedSingleStreamStrategy(),
        'nds': NonDiarizedSingleStreamStrategy(),

        'diarized-single': DiarizedSingleStreamStrategy(),
        'ds': DiarizedSingleStreamStrategy(),

        'non-diarized-multi': NonDiarizedMultiStreamStrategy(),
        'ndm': NonDiarizedMultiStreamStrategy(),

        'non-diarized-aligned': NonDiarizedAlignedFilesStrategy(),
        'nda': NonDiarizedAlignedFilesStrategy()
    })
    
    @staticmethod
    def get_strategy(transcription_strategy: str):
        strategy = TranscriptionStrategyFactory._strategy_mapping.get(transcription_strategy, None)
        if not strategy:
            raise ValueError(f"Incorrect transcription strategy: {transcription_strategy}!")
        return strategy
